aws_region         = "ap-south-1"
vpc_cidr_block     = "10.0.0.0/16"
public_subnets     = ["10.0.1.0/24", "10.0.2.0/24"]
private_subnets    = ["10.0.101.0/24", "10.0.102.0/24"]
availability_zones = ["ap-south-1a", "ap-south-1b"]
cluster_name       = "technosaffron-cluster"
cluster_version    = "1.33"
node_group_name    = "production-worker-nodes"
instance_type      = "t3.medium"
desired_size       = 3
max_size           = 3
min_size           = 3
project_name       = "blue-green-deployment"
